<%
wcs_system = ENV.fetch('WCS_HOST', '192.168.252.1')
cms_system = ENV.fetch('CMS_HOST', '192.168.252.1')
local_system = ENV.fetch('LOCAL_HOST', Socket.gethostbyname(Socket.gethostname).first)
puts '--------------------------------------------'
puts " WCS_HOST:     #{wcs_system}"
puts " CMS_HOST:     #{cms_system}"
puts " LOCAL_HOST:   #{local_system}"
puts '--------------------------------------------'
%>
---
driver:
  name: vagrant
  vagrantfiles:
    - ../../config/cachier.rb
    - ../../config/linked-clones.rb
  provider: virtualbox
  customize:
    memory: 512
    cpus: 1
  synced_folders:
    - ["./.kitchen/build", "/shared", "create: true"]
  network:
    - ['private_network',{ ip: '192.168.252.100' }]

provisioner:
  name: chef_solo
  require_chef_omnibus: "12.8.1"
  chef_omnibus_install_options: -d /tmp/vagrant-cache/chef-omnibus
  environments_path: ../../environments
  solo_rb:
    environment: kitchen

platforms:
- name: centos6-vagrant
  driver:
    box: coremedia/base
    box_url: 'https://atlas.hashicorp.com/coremedia/boxes/base'
    box_version: '1.16.0'

- name: centos7-vagrant
  driver:
    box: coremedia/base7
    box_url: 'https://atlas.hashicorp.com/coremedia/boxes/base7'
    box_version: '2.3.0'

suites:
# test suite for serverspec tests
- name: default
  # add platforms to test to this array, by default only one is listed so a simple kitchen converge will run this suite
  includes: [centos6-vagrant]
  run_list:
    - recipe[blueprint-base::reporting]
    - recipe[blueprint-proxy::default]
  attributes:
    blueprint:
      hostname: '192.168.252.100.xip.io'
      wcs:
        host: <%= wcs_system %>
      proxy:
        ssl_proxy_verify: false
        cms_host: <%= cms_system %>

 # test suite for local development
- name: development
  # add platforms to test to this array, by default only one is listed so a simple kitchen converge will run this suite
  includes: [centos7-vagrant]
  run_list:
    - recipe[blueprint-base::reporting]
    - recipe[blueprint-proxy::default]
  attributes:
    blueprint:
      hostname: '192.168.252.100.xip.io'
      wcs:
        host: <%= wcs_system %>
      proxy:
        ssl_proxy_verify: false
        cms_host: <%= cms_system %>
        virtual_host:
          shop-preview:
            headers:
            - 'RequestHeader set X-FragmentHostDevelopment http://<%= local_system %>:40980/blueprint/servlet/service/fragment/'
          shop:
            headers:
            - 'RequestHeader set X-FragmentHostDevelopment http://<%= local_system %>:42180/blueprint/servlet/service/fragment/'
          studio:
            context: ''

