version: "3.4"

# default environment variables for all spring-boot services
x-development-boot-envs:
  &development-boot-envs
  DEVELOPMENT_SETUP: "${DEVELOPMENT_SETUP:-false}"
  JAVA_DEBUG: "${JAVA_DEBUG:-false}"
  JAVA_DEBUG_SUSPEND: "${JAVA_DEBUG_SUSPEND:-false}"
  # enable entrypoint debugging i.e. set -x
  DEBUG_ENTRYPOINT: "${DEBUG_ENTRYPOINT:-false}"
  JAVA_HEAP: '128m'
  # writes heapdumps to /coremedia/heapdumps on oom exceptions. restart the container or mount a volume to
  # that directory to inspect the heapdumps
  HEAP_DUMP_ON_OOM: "${HEAP_DUMP_ON_OOM:-true}"
  # extracts the app at startup to speed up the annotation and property scanning of the classpath. The startup improvements
  # are around 2-3x faster. It is also the recommended way by Spring. With Spring-Boot 2.3 the spring-maven-plugin will
  # be able to build images with exploded layout.
  SPRING_BOOT_EXPLODED_APP: "${SPRING_BOOT_EXPLODED_APP:-true}"

# default logging configuration
x-logging:
        &default-logging
  options:
    max-size: '12m'
    max-file: '5'
  driver: json-file

services:
  commerce-adapter-wcs:
    image: ${COMMERCE_REPOSITORY_PREFIX:-coremedia}/commerce-adapter-wcs:${COMMERCE_ADAPTER_WCS_VERSION:-1.6.2}
    container_name: commerce-adapter-wcs
    restart: always
    logging: *default-logging
    networks:
      - backend
    ports:
      - 44365:6565
      - 44381:8081
      - 44305:5005
    environment:
      << : *development-boot-envs
      WCS_HOST: ${WCS_HOST}
      WCS_LINK_STOREFRONT_HOST: ${WCS_LINK_STOREFRONT_HOST}
      WCS_LINK_PRODUCT_MAX_URL_SEGMENTS: ${WCS_LINK_PRODUCT_MAX_URL_SEGMENTS:-7}
      WCS_USERNAME: ${WCS_USERNAME}
      WCS_PASSWORD: ${WCS_PASSWORD}
      SPRING_PROFILES: ${SPRING_PROFILES:-wcs-9.0}
      MANAGEMENT_HEALTH_STORES_ENABLED: ${MANAGEMENT_HEALTH_STORES_ENABLED:-true}

  studio-server:
    environment:
      COMMERCE_HUB_DATA_ENDPOINTS_WCS: ${COMMERCE_HUB_DATA_ENDPOINTS_WCS:-commerce-adapter-wcs:6565}
  cae-preview:
    environment:
      COMMERCE_HUB_DATA_ENDPOINTS_WCS: ${COMMERCE_HUB_DATA_ENDPOINTS_WCS:-commerce-adapter-wcs:6565}
  cae-live:
    environment:
      COMMERCE_HUB_DATA_ENDPOINTS_WCS: ${COMMERCE_HUB_DATA_ENDPOINTS_WCS:-commerce-adapter-wcs:6565}
  headless-server-preview:
    environment:
      COMMERCE_HUB_DATA_ENDPOINTS_WCS: ${COMMERCE_HUB_DATA_ENDPOINTS_WCS:-commerce-adapter-wcs:6565}
  headless-server-live:
    environment:
      COMMERCE_HUB_DATA_ENDPOINTS_WCS: ${COMMERCE_HUB_DATA_ENDPOINTS_WCS:-commerce-adapter-wcs:6565}
  content-feeder:
    environment:
      COMMERCE_HUB_DATA_ENDPOINTS_WCS: ${COMMERCE_HUB_DATA_ENDPOINTS_WCS:-commerce-adapter-wcs:6565}
