services:
  sfcc-proxy:
      image: ${REPOSITORY_PREFIX:-coremedia}/sfcc-proxy
      container_name: sfcc-proxy
      restart: always
      build:
        context: ../commerce-proxy
      networks:
        - backend
      environment:
        COMMERCE_SYSTEM: sfcc
        ENVIRONMENT_FQDN: ${ENVIRONMENT_FQDN:-docker.localhost}
        SFCC_HOST: ${SFCC_HOST}
        SFCC_SITEID: ${SFCC_SITEID:-SiteGenesisGlobal}
        CMS_PUBLIC_HOST: ${CMS_PUBLIC_HOST}

  cae-preview:
    environment:
      SFCC_HOST: ${SFCC_HOST}
      SFCC_CLIENTID: ${SFCC_CLIENTID}
      SFCC_CLIENTPASSWORD: ${SFCC_CLIENTPASSWORD}
      SPRING_PROFILES: ${SPRING_PROFILES:-dev-sfcc}
      LIVECONTEXT_SFCC_STOREFRONT_URL: https://shop-preview-sfcc.${ENVIRONMENT_FQDN:-docker.localhost}/on/demandware.store

  cae-live:
    environment:
      SFCC_HOST: ${SFCC_HOST}
      SFCC_CLIENTID: ${SFCC_CLIENTID}
      SFCC_CLIENTPASSWORD: ${SFCC_CLIENTPASSWORD}
      SPRING_PROFILES: ${SPRING_PROFILES:-dev-sfcc}
      LIVECONTEXT_SFCC_STOREFRONT_URL: https://shop-sfcc.${ENVIRONMENT_FQDN:-docker.localhost}/on/demandware.store

  studio-server:
    environment:
      SFCC_HOST: ${SFCC_HOST}
      SFCC_CLIENTID: ${SFCC_CLIENTID}
      SFCC_CLIENTPASSWORD: ${SFCC_CLIENTPASSWORD}

  traefik:
    environment:
      # Because the mock adapter is a development only feature, we can activate the actuator here
      ACTUATOR_COMMERCE_ADAPTER_SFCC: 'commerce-adapter-sfcc'
    volumes:
      - ../traefik/dynamic-configuration/development-commerce/sfcc-proxy.yml:/etc/traefik/dynamic/commerce/sfcc-proxy.yml
      - ../traefik/dynamic-configuration/development-commerce/sfcc-cae-live.yml:/etc/traefik/dynamic/commerce/sfcc-cae-live.yml

  overview:
    environment:
      COMMERCE_SFCC_ENABLED: "true"
      COMMERCE_SFCC_HOST: ${SFCC_HOST}
