services:
  content-management-server:
    volumes:
      - ../coremedia-keystore:/coremedia/.cmservices
    environment:
      ENCRYPTION_KEYSTORE_KEYSTOREPASSWORD: ${ENCRYPTION_KEYSTORE_KEYSTOREPASSWORD}
      ENCRYPTION_KEYSTORE_KEYALIAS: ${ENCRYPTION_KEYSTORE_KEYALIAS}
      ENCRYPTION_KEYSTORE_KEYPASSWORD: ${ENCRYPTION_KEYSTORE_KEYPASSWORD}

  master-live-server:
    volumes:
      - ../coremedia-keystore:/coremedia/.cmservices
    environment:
      ENCRYPTION_KEYSTORE_KEYSTOREPASSWORD: ${ENCRYPTION_KEYSTORE_KEYSTOREPASSWORD}
      ENCRYPTION_KEYSTORE_KEYALIAS: ${ENCRYPTION_KEYSTORE_KEYALIAS}
      ENCRYPTION_KEYSTORE_KEYPASSWORD: ${ENCRYPTION_KEYSTORE_KEYPASSWORD}

  workflow-server:
    volumes:
      - ../coremedia-keystore:/coremedia/.cmservices
    environment:
      ENCRYPTION_KEYSTORE_KEYSTOREPASSWORD: ${ENCRYPTION_KEYSTORE_KEYSTOREPASSWORD}
      ENCRYPTION_KEYSTORE_KEYALIAS: ${ENCRYPTION_KEYSTORE_KEYALIAS}
      ENCRYPTION_KEYSTORE_KEYPASSWORD: ${ENCRYPTION_KEYSTORE_KEYPASSWORD}

  content-feeder:
    volumes:
      - ../coremedia-keystore:/coremedia/.cmservices
    environment:
      ENCRYPTION_KEYSTORE_KEYSTOREPASSWORD: ${ENCRYPTION_KEYSTORE_KEYSTOREPASSWORD}
      ENCRYPTION_KEYSTORE_KEYALIAS: ${ENCRYPTION_KEYSTORE_KEYALIAS}
      ENCRYPTION_KEYSTORE_KEYPASSWORD: ${ENCRYPTION_KEYSTORE_KEYPASSWORD}

  cae-feeder-preview:
    volumes:
      - ../coremedia-keystore:/coremedia/.cmservices
    environment:
      ENCRYPTION_KEYSTORE_KEYSTOREPASSWORD: ${ENCRYPTION_KEYSTORE_KEYSTOREPASSWORD}
      ENCRYPTION_KEYSTORE_KEYALIAS: ${ENCRYPTION_KEYSTORE_KEYALIAS}
      ENCRYPTION_KEYSTORE_KEYPASSWORD: ${ENCRYPTION_KEYSTORE_KEYPASSWORD}

  cae-feeder-live:
    volumes:
      - ../coremedia-keystore:/coremedia/.cmservices
    environment:
      ENCRYPTION_KEYSTORE_KEYSTOREPASSWORD: ${ENCRYPTION_KEYSTORE_KEYSTOREPASSWORD}
      ENCRYPTION_KEYSTORE_KEYALIAS: ${ENCRYPTION_KEYSTORE_KEYALIAS}
      ENCRYPTION_KEYSTORE_KEYPASSWORD: ${ENCRYPTION_KEYSTORE_KEYPASSWORD}

  user-changes:
    volumes:
      - ../coremedia-keystore:/coremedia/.cmservices
    environment:
      ENCRYPTION_KEYSTORE_KEYSTOREPASSWORD: ${ENCRYPTION_KEYSTORE_KEYSTOREPASSWORD}
      ENCRYPTION_KEYSTORE_KEYALIAS: ${ENCRYPTION_KEYSTORE_KEYALIAS}
      ENCRYPTION_KEYSTORE_KEYPASSWORD: ${ENCRYPTION_KEYSTORE_KEYPASSWORD}

  elastic-worker:
    volumes:
      - ../coremedia-keystore:/coremedia/.cmservices
    environment:
      ENCRYPTION_KEYSTORE_KEYSTOREPASSWORD: ${ENCRYPTION_KEYSTORE_KEYSTOREPASSWORD}
      ENCRYPTION_KEYSTORE_KEYALIAS: ${ENCRYPTION_KEYSTORE_KEYALIAS}
      ENCRYPTION_KEYSTORE_KEYPASSWORD: ${ENCRYPTION_KEYSTORE_KEYPASSWORD}

  studio-server:
    volumes:
      - ../coremedia-keystore:/coremedia/.cmservices
    environment:
      ENCRYPTION_KEYSTORE_KEYSTOREPASSWORD: ${ENCRYPTION_KEYSTORE_KEYSTOREPASSWORD}
      ENCRYPTION_KEYSTORE_KEYALIAS: ${ENCRYPTION_KEYSTORE_KEYALIAS}
      ENCRYPTION_KEYSTORE_KEYPASSWORD: ${ENCRYPTION_KEYSTORE_KEYPASSWORD}

  cae-preview:
    volumes:
      - ../coremedia-keystore:/coremedia/.cmservices
    environment:
      ENCRYPTION_KEYSTORE_KEYSTOREPASSWORD: ${ENCRYPTION_KEYSTORE_KEYSTOREPASSWORD}
      ENCRYPTION_KEYSTORE_KEYALIAS: ${ENCRYPTION_KEYSTORE_KEYALIAS}
      ENCRYPTION_KEYSTORE_KEYPASSWORD: ${ENCRYPTION_KEYSTORE_KEYPASSWORD}

  replication-live-server:
    volumes:
      - ../coremedia-keystore:/coremedia/.cmservices
    environment:
      ENCRYPTION_KEYSTORE_KEYSTOREPASSWORD: ${ENCRYPTION_KEYSTORE_KEYSTOREPASSWORD}
      ENCRYPTION_KEYSTORE_KEYALIAS: ${ENCRYPTION_KEYSTORE_KEYALIAS}
      ENCRYPTION_KEYSTORE_KEYPASSWORD: ${ENCRYPTION_KEYSTORE_KEYPASSWORD}

  cae-live:
    volumes:
      - ../coremedia-keystore:/coremedia/.cmservices
    environment:
      ENCRYPTION_KEYSTORE_KEYSTOREPASSWORD: ${ENCRYPTION_KEYSTORE_KEYSTOREPASSWORD}
      ENCRYPTION_KEYSTORE_KEYALIAS: ${ENCRYPTION_KEYSTORE_KEYALIAS}
      ENCRYPTION_KEYSTORE_KEYPASSWORD: ${ENCRYPTION_KEYSTORE_KEYPASSWORD}

  management-tools:
    volumes:
      - ../coremedia-keystore:/coremedia/.cmservices
    environment:
      ENCRYPTION_KEYSTORE_KEYSTOREPASSWORD: ${ENCRYPTION_KEYSTORE_KEYSTOREPASSWORD}
      ENCRYPTION_KEYSTORE_KEYALIAS: ${ENCRYPTION_KEYSTORE_KEYALIAS}
      ENCRYPTION_KEYSTORE_KEYPASSWORD: ${ENCRYPTION_KEYSTORE_KEYPASSWORD}

  headless-server-preview:
    volumes:
      - ../coremedia-keystore:/coremedia/.cmservices
    environment:
      ENCRYPTION_KEYSTORE_KEYSTOREPASSWORD: ${ENCRYPTION_KEYSTORE_KEYSTOREPASSWORD}
      ENCRYPTION_KEYSTORE_KEYALIAS: ${ENCRYPTION_KEYSTORE_KEYALIAS}
      ENCRYPTION_KEYSTORE_KEYPASSWORD: ${ENCRYPTION_KEYSTORE_KEYPASSWORD}

  headless-server-live:
    volumes:
      - ../coremedia-keystore:/coremedia/.cmservices
    environment:
      ENCRYPTION_KEYSTORE_KEYSTOREPASSWORD: ${ENCRYPTION_KEYSTORE_KEYSTOREPASSWORD}
      ENCRYPTION_KEYSTORE_KEYALIAS: ${ENCRYPTION_KEYSTORE_KEYALIAS}
      ENCRYPTION_KEYSTORE_KEYPASSWORD: ${ENCRYPTION_KEYSTORE_KEYPASSWORD}
