x-logging:
  &default-logging
  options:
    max-size: '12m'
    max-file: '5'
  driver: json-file

services:
  studio-packages-proxy:
    image: ${REPOSITORY_PREFIX:-coremedia}/studio-packages-proxy
    container_name: studio-packages-proxy
    restart: always
    logging: *default-logging
    networks:
      - backend

  traefik:
    environment:
      ACTUATOR_STUDIO_PACKAGES_PROXY: 'studio-packages-proxy'
    volumes:
      - ../traefik/dynamic-configuration/default/studio-packages-proxy.yml:/etc/traefik/dynamic/default/studio-packages-proxy.yml
