[template]
src   = "loglevel.html.tmpl"
dest  = "/usr/share/nginx/html/assets/loglevel.html"
keys  = [
        "/studio/packages/proxy/enabled",
        "/commerce/mock/enabled",
        "/commerce/sfcc/enabled",
        "/commerce/hybris/enabled",
        "/commerce/wcs/enabled"
]
