---
driver:
  name: vagrant
  vagrantfiles: ['../../config/cachier.rb']
  box: coremedia/base
  provider: virtualbox
  customize:
    memory: 512
    cpus: 1
  synced_folders:
    - ["./.kitchen/build", "/shared", "create: true"]
  network:
    - ['private_network',{ ip: '192.168.252.100' }]
provisioner:
  name: chef_solo
  require_chef_omnibus: "12.8.1"
  environments_path: ../../environments
  solo_rb:
    environment: kitchen

platforms:
- name: centos6-vagrant
  driver:
    box: coremedia/base
    box_url: 'http://boxes.coremedia.com/vagrant/coremedia-centos6-base-box.json'

- name: centos7-vagrant
  driver:
    box: coremedia/base7
    box_url: 'http://boxes.coremedia.com/vagrant/coremedia-centos7-base-box.json'

suites:
  - name: default
    includes: [centos6-vagrant]
    run_list:
      - recipe[blueprint-base::default]

suites:
- name: reporting
  includes: [centos6-vagrant]
  run_list:
    - recipe[blueprint-base::reporting]
