---
driver:
  name: vagrant
  vagrantfiles:
    - ../../config/cachier.rb
    - ../../config/linked-clones.rb
  provider: virtualbox
  customize:
    memory: 1024
    cpus: 1
  synced_folders:
    - ["./.kitchen/build", "/shared", "create: true"]
  network:
    - ['private_network',{ ip: '192.168.252.110' }]

provisioner:
  name: chef_solo
  require_chef_omnibus: "12.8.1"
  environments_path: ../../environments
  solo_rb:
    environment: kitchen

platforms:
- name: centos7-vagrant
  driver:
    box: coremedia/base7
    box_url: 'https://atlas.hashicorp.com/coremedia/boxes/base7'
    box_version: '2.3.0'

suites:
- name: default
  # add platforms to test to this array, by default only one is listed so a simple kitchen converge will run this suite
  #includes: [centos7-vagrant]
  run_list:
    - recipe[blueprint-yum::default]
    - recipe[blueprint-mysql::server]
    - recipe[blueprint-dev-tooling::databases]
  attributes:
    blueprint:
      dev:
        db:
          host: localhost
          type: mysql