---
driver:
  name: vagrant
  vagrantfiles:
    - ../../config/cachier.rb
    - ../../config/linked-clones.rb
  provider: virtualbox
  customize:
    memory: 1024
    cpus: 1
  synced_folders:
    - ["./build", "/shared", "create: true"]
  network:
    - ['private_network',{ ip: '192.168.252.100' }]

provisioner:
  name: chef_solo
  require_chef_omnibus: "12.8.1"
  environments_path: ../../environments
  solo_rb:
    environment: kitchen

platforms:
- name: centos6-vagrant
  driver:
    box: coremedia/base
    box_url: 'https://atlas.hashicorp.com/coremedia/boxes/base'
    box_version: '1.16.0'

- name: centos7-vagrant
  driver:
    box: coremedia/base7
    box_url: 'https://atlas.hashicorp.com/coremedia/boxes/base7'
    box_version: '2.1.0'

suites:
- name: default
  # add platforms to test to this array, by default only one is listed so a simple kitchen converge will run this suite
  includes: [centos7-vagrant]
  run_list:
    - recipe[blueprint-mongodb::default]
