---
driver:
  name: vagrant
  vagrantfiles:
    - ../../config/cachier.rb
    - ../../config/linked-clones.rb
  provider: virtualbox
  customize:
    memory: 1024
    cpus: 1
  synced_folders:
    - ["./.kitchen/build", "/shared", "create: true"]
  network:
    - ['private_network',{ ip: '192.168.252.109' }]

provisioner:
  name: chef_solo
  require_chef_omnibus: "12.8.1"
  environments_path: ../../environments
  solo_rb:
    environment: kitchen

platforms:
- name: centos6-vagrant
  driver:
    box: coremedia/base
    box_url: 'https://atlas.hashicorp.com/coremedia/boxes/base'
    box_version: '1.16.0'

- name: centos7-vagrant
  driver:
    box: coremedia/base7
    box_url: 'https://atlas.hashicorp.com/coremedia/boxes/base7'
    box_version: '2.3.0'

suites:
- name: default
  # add platforms to test to this array, by default only one is listed so a simple kitchen converge will run this suite
  includes: [centos7-vagrant]
  run_list:
    - recipe[blueprint-mongodb::default]

- name: mongod_3_2
  run_list:
    - recipe[blueprint-mongodb::default]
  attributes:
    mongodb:
      yum:
        mirrorlist: "https://s3-eu-west-1.amazonaws.com/mirrors.coremedia.com/repo.mongodb.org/yum/redhat/$releasever/mongodb-org/3.2/$basearch/mirror"
    mongodb3:
      version: '3.2.11'
      mongod:
        disable-transparent-hugepages: true

- name: mongod_3_4
  run_list:
    - recipe[blueprint-mongodb::default]
  attributes:
    mongodb:
      yum:
        baseurl: https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/3.4/x86_64
    mongodb3:
      version: '3.4.1'
      mongod:
        disable-transparent-hugepages: false
