---
driver:
  name: vagrant
  vagrantfiles:
    - config/cachier.rb
    - config/linked-clones.rb
  provider: virtualbox
  customize:
    memory: 8192
    cpus: 2
  synced_folders:
    - ["./build", "/shared", "create: true"]
    - ["~/.m2/repository", "/maven-repo"]
  network:
    - ['private_network',{ ip: '192.168.252.100' }]

provisioner:
  name: chef_solo
  require_chef_omnibus: "12.8.1"
  chef_omnibus_install_options: -d /tmp/vagrant-cache/chef-omnibus
  environments_path: ../../environments
  solo_rb:
    environment: kitchen

platforms:
- name: centos6-vagrant
  driver:
    box: coremedia/base
    box_url: 'https://atlas.hashicorp.com/coremedia/boxes/base'
    box_version: '1.16.0'

- name: centos7-vagrant
  driver:
    box: coremedia/base7
    box_url: 'https://atlas.hashicorp.com/coremedia/boxes/base7'
    box_version: '2.1.0'

suites:
- name: tomcat-75
  # add platforms to test to this array, by default only one is listed so a simple kitchen converge will run this suite
  includes: [centos6-vagrant]
  run_list:
    - recipe[blueprint-tools::content-management-server-tools]
    - recipe[blueprint-tools::master-live-server-tools]
    - recipe[blueprint-tools::replication-live-server-tools]
    - recipe[blueprint-tools::workflow-server-tools]
    - recipe[blueprint-tools::css-importer-tools]
    - recipe[blueprint-tools::caefeeder-live-tools]
    - recipe[blueprint-tools::caefeeder-preview-tools]
  attributes:
    blueprint:
      hostname: '192.168.252.100.xip.io'