---
driver:
  name: vagrant
  vagrantfiles:
    - config/cachier.rb
    - config/linked-clones.rb
  provider: virtualbox
  customize:
    memory: 8192
    cpus: 2
  synced_folders:
    - ["./build", "/shared", "create: true"]
    - ["~/.m2/repository", "/maven-repo"]
  network:
    - ['private_network',{ ip: '192.168.252.100' }]

provisioner:
  name: chef_solo
  require_chef_omnibus: "12.8.1"
  chef_omnibus_install_options: -d /tmp/vagrant-cache/chef-omnibus
  environments_path: ../../environments
  solo_rb:
    environment: kitchen

platforms:
- name: centos6-vagrant
  driver:
    box: coremedia/base
    box_url: 'https://atlas.hashicorp.com/coremedia/boxes/base'
    box_version: '1.16.0'

- name: centos7-vagrant
  driver:
    box: coremedia/base7
    box_url: 'https://atlas.hashicorp.com/coremedia/boxes/base7'
    box_version: '2.1.0'

suites:
- name: default
  # add platforms to test to this array, by default only one is listed so a simple kitchen converge will run this suite
  includes: [centos6-vagrant]
  run_list:
    - recipe[blueprint-tomcat::default]
  attributes:
    blueprint:
      libjpeg_turbo_path: '_libjpeg_turbo_path_'
      tomcat:
        start_services: false
        jvm_GC_flags: '_jvm_GC_flags_'
        jvm_agent_opts: '_jvm_agent_opts_'
        content-management-server:
          catalina_opts: '_catalina_opts'
        master-live-server:
          catalina_opts: '_catalina_opts'
        workflow-server:
          catalina_opts: '_catalina_opts'
        replication-live-server:
          catalina_opts: '_catalina_opts'
        adobe-drive-server:
          catalina_opts: '_catalina_opts'
        caefeeder-preview:
          catalina_opts: '_catalina_opts'
        caefeeder-live:
          catalina_opts: '_catalina_opts'
        content-feeder:
          catalina_opts: '_catalina_opts'
        studio:
          catalina_opts: '_catalina_opts'
        cae-preview:
          catalina_opts: '_catalina_opts'
        user-changes:
          catalina_opts: '_catalina_opts'
        elastic-worker:
          catalina_opts: '_catalina_opts'
        solr:
          catalina_opts: '_catalina_opts'
        sitemanager:
          catalina_opts: '_catalina_opts'
        cae-live:
          instances: 2
          heap: '_heap_default_'
          perm: '_perm_default_'
        cae-live-1:
          catalina_opts: '_catalina_opts'
        cae-live-2:
          port_prefix: 9999
          heap: '_heap_override_'
          perm: '_perm_override_'
          catalina_opts: '_catalina_opts'
      webapps:
        cae-live:
          application.properties:
            foo: '_property_default_'
        cae-live-2:
          artifact_id: 'studio-webapp'
          application.properties:
            foo: '_property_override_'