packages:
  - "apps/main/app"
  - "apps/main/base-app"
  - "apps/main/blueprint-forms"
  - "apps/main/blueprint-studio-theme"
  - "apps/main/controlroom-studio-plugin"
  - "apps/main/ec-studio"
  - "apps/main/ec-studio-model"
  - "apps/main/ec-studio-test-helper"
  - "apps/main/extension-config/extension-dependencies"
  - "apps/main/extension-config/static-extension-dependencies"
  - "apps/main/extensions/alx"
  - "apps/main/extensions/alx-google"
  - "apps/main/extensions/alx-webtrends"
  - "apps/main/extensions/am"
  - "apps/main/extensions/catalog"
  - "apps/main/extensions/content-hub-default/content-hub-rss"
  - "apps/main/extensions/content-hub-default/content-hub-youtube"
  - "apps/main/extensions/create-from-template"
  - "apps/main/extensions/custom-topic-pages"
  - "apps/main/extensions/ecommerce-ibm"
  - "apps/main/extensions/es"
  - "apps/main/extensions/es-alx"
  - "apps/main/extensions/feedback-hub"
  - "apps/main/extensions/lc-asset"
  - "apps/main/extensions/lc-es"
  - "apps/main/extensions/lc-p13n"
  - "apps/main/extensions/lc/lc-studio"
  - "apps/main/extensions/lc/lc-studio-test-helper"
  - "apps/main/extensions/optimizely"
  - "apps/main/extensions/osm"
  - "apps/main/extensions/p13n"
  - "apps/main/extensions/taxonomy"
  - "apps/main/extensions/validators"
  - "global/studio"
